services:
  redis:
    image: redis:7-alpine
    container_name: stackquiz-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  #
  stackquiz-api:
    build: .
    container_name: stackquiz-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    restart: unless-stopped

volumes:
  redis_data:
