keycloak:
  realm: stackquiz
  server-url: https://keycloak-prod.rattanakmony.com
  client-id: admin-cli
  client-secret: i3DAFVHsFMXrM1S1rg7VgX55ue3kZnUo

app:
  default-role: ORGANIZER

spring:
  application:
    name: stackquiz-api
  
  threads:
    virtual:
      enabled: true
  
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
  
  datasource:
    #    url: jdbc:postgresql://dpg-d2inormr433s73e0p820-a.oregon-postgres.render.com:5432/stack_quiz_db  
    #    username: stack_quiz_db_user    #    password: B30kvFA40SWgA3YQd2HkjPjDTkiU1srO    #    driver-class-name: org.postgresql.Driver    url: jdbc:postgresql://localhost:5432/stack_quiz_db  
    url: jdbc:postgresql://localhost:4000/bankdb
    username: postgres
    password: seng4321
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
  
  data:
    redis:
      host: 35.247.128.230
      port: 6379
      database: 0
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms
  
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-prod.rattanakmony.com/realms/stackquiz
server:
  port: 9999
